# config.yaml

huggingface:
  token: "hf_token"  # Replace with your actual Hugging Face token
  transcribe_model_path: "openai/whisper-large-v3" # Local pretrained model path or model name from HuggingFace
  diarization_model: "pyannote/speaker-diarization-3.1"

languages:
  - English
  - Chinese
  - German
  - Spanish
  - Russian
  - Korean
  - French
  - Japanese
  - Portuguese
  - Turkish
  - Polish
  - Catalan
  - Dutch
  - Arabic
  - Swedish
  - Italian
  - Indonesian
  - Hindi
  - Finnish
  - Vietnamese
  - Hebrew
  - Ukrainian
  - Greek
  - Malay
  - Czech
  - Romanian
  - Danish
  - Hungarian
  - Tamil
  - Norwegian
  - Thai
  - Urdu
  - Croatian
  - Bulgarian
  - Lithuanian
  - Latin
  - Māori
  - Malayalam
  - Welsh
  - Slovak
  - Telugu
  - Persian
  - Latvian
  - Bengali
  - Serbian
  - Azerbaijani
  - Slovenian
  - Kannada
  - Estonian
  - Macedonian
  - Breton
  - Basque
  - Icelandic
  - Armenian
  - Nepali
  - Mongolian
  - Bosnian
  - Kazakh
  - Albanian
  - Swahili
  - Galician
  - Marathi
  - Panjabi
  - Sinhala
  - Khmer
  - Shona
  - Yoruba
  - Somali
  - Afrikaans
  - Occitan
  - Georgian
  - Belarusian
  - Tajik
  - Sindhi
  - Gujarati
  - Amharic
  - Yiddish
  - Lao
  - Uzbek
  - Faroese
  - Haitian
  - Pashto
  - Turkmen
  - Norwegian Nynorsk
  - Maltese
  - Sanskrit
  - Luxembourgish
  - Burmese
  - Tibetan
  - Tagalog
  - Malagasy
  - Assamese
  - Tatar
  - Hawaiian
  - Lingala
  - Hausa
  - Bashkir
  - Sundanese
